### ISSUE TITLE
Barrier Asset

### ISSUE THREAD

**Issue by rszcodronski** [Azure/opendigitaltwins-building#21]
The [Barrier Asset](https://github.com/Azure/opendigitaltwins-building/blob/master/Ontology/Asset/ArchitecturalAsset/BarrierAsset.json) has a property `type` (Enum: Interior, Exterior) which isn't a very good representation of what it is describing. Instead, I propose that we change this to be named `service` (Enum: Interior, Exterior) to better align with how the term `service` is being used throughout the ontology. The term `type` is being used throughout the ontology to define different styles (aka type) of that particular asset you may have and not its placement context (aka service).

Willow has extended the REC Barrier Asset model like [this](https://github.com/WillowInc/opendigitaltwins-building/blob/main/Ontology/Willow/Asset/Architectural%20Asset/Barrier%20Asset/BarrierAsset.json) to include a `service` property.

**Comment by hammar** [comment]
Makes sense to me. I'll integrate in upstream OWL-REC and that should follow along when we next regenerate models w/ OWL2DTDL (presently possibly blocked by my comment on the Space components in the other PR)

**Comment by hammar** [comment]
Closed in 6c52c1aea918bcd155d36d41b37d2e6c6bd67d87
