### ISSUE TITLE
"dtmi:digitaltwins:rec_3_3:asset:Server;1" extends missing "dtmi:digitaltwins:rec_3_3:asset:ITHardware;1"

### ISSUE THREAD

**Issue by nazar-kuzo** [Azure/opendigitaltwins-building#22]
Current ontology models failed validation due to "dtmi:digitaltwins:rec_3_3:asset:Server;1" (Asset\Equipment\ICT\ITHardwareEquipment\Server.json) extends missing "dtmi:digitaltwins:rec_3_3:asset:ITHardware;1".

I assume there is a typo and it should reference "dtmi:digitaltwins:rec_3_3:asset:ICTHardware;1" (Asset\Equipment\ICT\ITCHardware.json), but there is one more inconsistency, file name (ITCHardware) is not matching the declaring interface (ICTHardware).

**Comment by akshayj-MSFT** [comment]
Thanks for reporting this.

Fixed this with this commit: https://github.com/Azure/opendigitaltwins-building/commit/cb93b123fdd7d552784996232ff1ee06ee1b99e4
