### ISSUE TITLE
LogicalDevice interface is missing "hasPart" relationship type

### ISSUE THREAD

**Issue by nazar-kuzo** [Azure/opendigitaltwins-building#30]
LogicalDevice interface is missing "hasPart" relationship type which is an inverse of: "isPartOf". In contrast, Assets, Spaces, etc have both relationships.

**Comment by hammar** [comment]
Good catch, that is a mistake that needs to be rectified. I'll update the upstream OWL models and regenerate in https://github.com/Azure/opendigitaltwins-building/pull/31. Thanks!
