### ISSUE TITLE
OntologyDiagram.JPG  Space Extends Building or the other way around? Arrows in the wrong direction perhaps?

### ISSUE THREAD

**Issue by saegen** [Azure/opendigitaltwins-building#32]
Could be wrong..

Sincerely Tomas Hesse

**Comment by hammar** [comment]
Hi,

Pardon the delayed response, workload has been heavier than usual. Good catch, that image is incorrect w.r.t. arrow directions on "extends". Perhaps a typical UML subclassing arrow could be used to further clarify meaning. @alinamstanciu, do you have the original diagram source and can fix? Alternatively, send that file (Visio?) over to me and I can do it.
