### ISSUE TITLE
Visualization link seems to be down

### ISSUE THREAD

**Issue by rajat-packt** [Azure/opendigitaltwins-building#66]
Hey! 
The ontology visualization link in the readme (this one: http://www.visualdataweb.de/webvowl/#iri=https://w3id.org/rec/full/3.3/)
seems to be down or incorrect

**Comment by hammar** [comment]
Thanks for noticing and reporting; it appears the external service that hosts the WebVOWL visualizer went down, and the community had a new version put up at another host. I've redirected the link.
