### ISSUE TITLE
No model names for some DTDL models

### ISSUE THREAD

**Issue by ogiel** [Azure/opendigitaltwins-building#79]
Small issue, the model names are missing for the following models:
- DamperStatusSensor
- FanStatusSensor
- FireExtinguisherRemovedSensor
- FireExtinguisherTroubleSensor
- LeakSensor

Is there any info yet about when DTDL v3 + REC4 will be released? This repo still contains DTDL v3 as the latest commit and it's not possible to upload these models.

**Comment by hammar** [comment]
Hi,

Those models are in the 1.0 release of this repository, linked from the "Releases" page. 

For REC4 development, see https://github.com/RealEstateCore/rec where we hope to have a GA release very shortly (weeks, not months). It is presently DTDLv2 so should be able to run in e.g., Azure Digital Twins or other DTDL platforms.

**Comment by ogiel** [comment]
Yes, I noticed the DTDLv2 in the jsonld format (which also can't be uploaded right away) but just changing the extension to .json worked. I'm really looking forward to the GA of REC 4 and DTDLv3.
