### ISSUE TITLE
Errors about browsing to [https://localhost:5001]

### ISSUE THREAD

**Issue by zhingoll** [Azure/opendigitaltwins-building#82]
Hi all,
Before running this project, the relevant files have been configured according to readme.md. 
Why do the following errors still occur?

![image](https://user-images.githubusercontent.com/113612424/234014022-dbe3bc01-7ce3-45c3-a42a-8e5b28b3c3e4.png)
![image](https://user-images.githubusercontent.com/113612424/234017081-a70296ad-74e2-4309-8cdd-da9679534e7e.png)
![image](https://user-images.githubusercontent.com/113612424/234017449-32f4202b-6a5a-4003-9e05-95f07719d043.png)

Thanks!

**Comment by hammar** [comment]
I do not believe that this error report derives from code provided through this model repository. It seems to refer to an authentication issue, possibly in an ADT model visualization tool. I'd advise to verify authentication/authorization configurations, and if warranted, raising an issue with the maintainers of the tool that is failing.
